//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: terra/oracle/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the oracle Msg service.
///
/// Usage: instantiate `Terra_Oracle_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Terra_Oracle_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Terra_Oracle_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func aggregateExchangeRatePrevote(
    _ request: Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote, Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse>

  func aggregateExchangeRateVote(
    _ request: Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote, Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse>

  func delegateFeedConsent(
    _ request: Terra_Oracle_V1beta1_MsgDelegateFeedConsent,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgDelegateFeedConsent, Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse>
}

extension Terra_Oracle_V1beta1_MsgClientProtocol {
  internal var serviceName: String {
    return "terra.oracle.v1beta1.Msg"
  }

  /// AggregateExchangeRatePrevote defines a method for submitting
  /// aggregate exchange rate prevote
  ///
  /// - Parameters:
  ///   - request: Request to send to AggregateExchangeRatePrevote.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func aggregateExchangeRatePrevote(
    _ request: Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote, Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse> {
    return self.makeUnaryCall(
      path: "/terra.oracle.v1beta1.Msg/AggregateExchangeRatePrevote",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAggregateExchangeRatePrevoteInterceptors() ?? []
    )
  }

  /// AggregateExchangeRateVote defines a method for submitting
  /// aggregate exchange rate vote
  ///
  /// - Parameters:
  ///   - request: Request to send to AggregateExchangeRateVote.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func aggregateExchangeRateVote(
    _ request: Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote, Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse> {
    return self.makeUnaryCall(
      path: "/terra.oracle.v1beta1.Msg/AggregateExchangeRateVote",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAggregateExchangeRateVoteInterceptors() ?? []
    )
  }

  /// DelegateFeedConsent defines a method for setting the feeder delegation
  ///
  /// - Parameters:
  ///   - request: Request to send to DelegateFeedConsent.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func delegateFeedConsent(
    _ request: Terra_Oracle_V1beta1_MsgDelegateFeedConsent,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Oracle_V1beta1_MsgDelegateFeedConsent, Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse> {
    return self.makeUnaryCall(
      path: "/terra.oracle.v1beta1.Msg/DelegateFeedConsent",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDelegateFeedConsentInterceptors() ?? []
    )
  }
}

internal protocol Terra_Oracle_V1beta1_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'aggregateExchangeRatePrevote'.
  func makeAggregateExchangeRatePrevoteInterceptors() -> [ClientInterceptor<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote, Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse>]

  /// - Returns: Interceptors to use when invoking 'aggregateExchangeRateVote'.
  func makeAggregateExchangeRateVoteInterceptors() -> [ClientInterceptor<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote, Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse>]

  /// - Returns: Interceptors to use when invoking 'delegateFeedConsent'.
  func makeDelegateFeedConsentInterceptors() -> [ClientInterceptor<Terra_Oracle_V1beta1_MsgDelegateFeedConsent, Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse>]
}

internal final class Terra_Oracle_V1beta1_MsgClient: Terra_Oracle_V1beta1_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Terra_Oracle_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the terra.oracle.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Terra_Oracle_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the oracle Msg service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Terra_Oracle_V1beta1_MsgProvider: CallHandlerProvider {
  var interceptors: Terra_Oracle_V1beta1_MsgServerInterceptorFactoryProtocol? { get }

  /// AggregateExchangeRatePrevote defines a method for submitting
  /// aggregate exchange rate prevote
  func aggregateExchangeRatePrevote(request: Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse>

  /// AggregateExchangeRateVote defines a method for submitting
  /// aggregate exchange rate vote
  func aggregateExchangeRateVote(request: Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse>

  /// DelegateFeedConsent defines a method for setting the feeder delegation
  func delegateFeedConsent(request: Terra_Oracle_V1beta1_MsgDelegateFeedConsent, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse>
}

extension Terra_Oracle_V1beta1_MsgProvider {
  internal var serviceName: Substring { return "terra.oracle.v1beta1.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AggregateExchangeRatePrevote":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote>(),
        responseSerializer: ProtobufSerializer<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse>(),
        interceptors: self.interceptors?.makeAggregateExchangeRatePrevoteInterceptors() ?? [],
        userFunction: self.aggregateExchangeRatePrevote(request:context:)
      )

    case "AggregateExchangeRateVote":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote>(),
        responseSerializer: ProtobufSerializer<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse>(),
        interceptors: self.interceptors?.makeAggregateExchangeRateVoteInterceptors() ?? [],
        userFunction: self.aggregateExchangeRateVote(request:context:)
      )

    case "DelegateFeedConsent":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Oracle_V1beta1_MsgDelegateFeedConsent>(),
        responseSerializer: ProtobufSerializer<Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse>(),
        interceptors: self.interceptors?.makeDelegateFeedConsentInterceptors() ?? [],
        userFunction: self.delegateFeedConsent(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Terra_Oracle_V1beta1_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'aggregateExchangeRatePrevote'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAggregateExchangeRatePrevoteInterceptors() -> [ServerInterceptor<Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevote, Terra_Oracle_V1beta1_MsgAggregateExchangeRatePrevoteResponse>]

  /// - Returns: Interceptors to use when handling 'aggregateExchangeRateVote'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAggregateExchangeRateVoteInterceptors() -> [ServerInterceptor<Terra_Oracle_V1beta1_MsgAggregateExchangeRateVote, Terra_Oracle_V1beta1_MsgAggregateExchangeRateVoteResponse>]

  /// - Returns: Interceptors to use when handling 'delegateFeedConsent'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDelegateFeedConsentInterceptors() -> [ServerInterceptor<Terra_Oracle_V1beta1_MsgDelegateFeedConsent, Terra_Oracle_V1beta1_MsgDelegateFeedConsentResponse>]
}
