//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: terra/market/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Terra_Market_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Terra_Market_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Terra_Market_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func swap(
    _ request: Terra_Market_V1beta1_QuerySwapRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Market_V1beta1_QuerySwapRequest, Terra_Market_V1beta1_QuerySwapResponse>

  func terraPoolDelta(
    _ request: Terra_Market_V1beta1_QueryTerraPoolDeltaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Market_V1beta1_QueryTerraPoolDeltaRequest, Terra_Market_V1beta1_QueryTerraPoolDeltaResponse>

  func params(
    _ request: Terra_Market_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Market_V1beta1_QueryParamsRequest, Terra_Market_V1beta1_QueryParamsResponse>
}

extension Terra_Market_V1beta1_QueryClientProtocol {
  internal var serviceName: String {
    return "terra.market.v1beta1.Query"
  }

  /// Swap returns simulated swap amount.
  ///
  /// - Parameters:
  ///   - request: Request to send to Swap.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func swap(
    _ request: Terra_Market_V1beta1_QuerySwapRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Market_V1beta1_QuerySwapRequest, Terra_Market_V1beta1_QuerySwapResponse> {
    return self.makeUnaryCall(
      path: "/terra.market.v1beta1.Query/Swap",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSwapInterceptors() ?? []
    )
  }

  /// TerraPoolDelta returns terra_pool_delta amount.
  ///
  /// - Parameters:
  ///   - request: Request to send to TerraPoolDelta.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func terraPoolDelta(
    _ request: Terra_Market_V1beta1_QueryTerraPoolDeltaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Market_V1beta1_QueryTerraPoolDeltaRequest, Terra_Market_V1beta1_QueryTerraPoolDeltaResponse> {
    return self.makeUnaryCall(
      path: "/terra.market.v1beta1.Query/TerraPoolDelta",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTerraPoolDeltaInterceptors() ?? []
    )
  }

  /// Params queries all parameters.
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func params(
    _ request: Terra_Market_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Market_V1beta1_QueryParamsRequest, Terra_Market_V1beta1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: "/terra.market.v1beta1.Query/Params",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }
}

internal protocol Terra_Market_V1beta1_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'swap'.
  func makeSwapInterceptors() -> [ClientInterceptor<Terra_Market_V1beta1_QuerySwapRequest, Terra_Market_V1beta1_QuerySwapResponse>]

  /// - Returns: Interceptors to use when invoking 'terraPoolDelta'.
  func makeTerraPoolDeltaInterceptors() -> [ClientInterceptor<Terra_Market_V1beta1_QueryTerraPoolDeltaRequest, Terra_Market_V1beta1_QueryTerraPoolDeltaResponse>]

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Terra_Market_V1beta1_QueryParamsRequest, Terra_Market_V1beta1_QueryParamsResponse>]
}

internal final class Terra_Market_V1beta1_QueryClient: Terra_Market_V1beta1_QueryClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Terra_Market_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the terra.market.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Terra_Market_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Terra_Market_V1beta1_QueryProvider: CallHandlerProvider {
  var interceptors: Terra_Market_V1beta1_QueryServerInterceptorFactoryProtocol? { get }

  /// Swap returns simulated swap amount.
  func swap(request: Terra_Market_V1beta1_QuerySwapRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Market_V1beta1_QuerySwapResponse>

  /// TerraPoolDelta returns terra_pool_delta amount.
  func terraPoolDelta(request: Terra_Market_V1beta1_QueryTerraPoolDeltaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Market_V1beta1_QueryTerraPoolDeltaResponse>

  /// Params queries all parameters.
  func params(request: Terra_Market_V1beta1_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Market_V1beta1_QueryParamsResponse>
}

extension Terra_Market_V1beta1_QueryProvider {
  internal var serviceName: Substring { return "terra.market.v1beta1.Query" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Swap":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Market_V1beta1_QuerySwapRequest>(),
        responseSerializer: ProtobufSerializer<Terra_Market_V1beta1_QuerySwapResponse>(),
        interceptors: self.interceptors?.makeSwapInterceptors() ?? [],
        userFunction: self.swap(request:context:)
      )

    case "TerraPoolDelta":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Market_V1beta1_QueryTerraPoolDeltaRequest>(),
        responseSerializer: ProtobufSerializer<Terra_Market_V1beta1_QueryTerraPoolDeltaResponse>(),
        interceptors: self.interceptors?.makeTerraPoolDeltaInterceptors() ?? [],
        userFunction: self.terraPoolDelta(request:context:)
      )

    case "Params":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Market_V1beta1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Terra_Market_V1beta1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        userFunction: self.params(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Terra_Market_V1beta1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'swap'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSwapInterceptors() -> [ServerInterceptor<Terra_Market_V1beta1_QuerySwapRequest, Terra_Market_V1beta1_QuerySwapResponse>]

  /// - Returns: Interceptors to use when handling 'terraPoolDelta'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTerraPoolDeltaInterceptors() -> [ServerInterceptor<Terra_Market_V1beta1_QueryTerraPoolDeltaRequest, Terra_Market_V1beta1_QueryTerraPoolDeltaResponse>]

  /// - Returns: Interceptors to use when handling 'params'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeParamsInterceptors() -> [ServerInterceptor<Terra_Market_V1beta1_QueryParamsRequest, Terra_Market_V1beta1_QueryParamsResponse>]
}
