//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: terra/wasm/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the oracle Msg service.
///
/// Usage: instantiate `Terra_Wasm_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Terra_Wasm_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Terra_Wasm_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func storeCode(
    _ request: Terra_Wasm_V1beta1_MsgStoreCode,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgStoreCode, Terra_Wasm_V1beta1_MsgStoreCodeResponse>

  func migrateCode(
    _ request: Terra_Wasm_V1beta1_MsgMigrateCode,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgMigrateCode, Terra_Wasm_V1beta1_MsgMigrateCodeResponse>

  func instantiateContract(
    _ request: Terra_Wasm_V1beta1_MsgInstantiateContract,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgInstantiateContract, Terra_Wasm_V1beta1_MsgInstantiateContractResponse>

  func executeContract(
    _ request: Terra_Wasm_V1beta1_MsgExecuteContract,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgExecuteContract, Terra_Wasm_V1beta1_MsgExecuteContractResponse>

  func migrateContract(
    _ request: Terra_Wasm_V1beta1_MsgMigrateContract,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgMigrateContract, Terra_Wasm_V1beta1_MsgMigrateContractResponse>

  func updateContractAdmin(
    _ request: Terra_Wasm_V1beta1_MsgUpdateContractAdmin,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgUpdateContractAdmin, Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse>

  func clearContractAdmin(
    _ request: Terra_Wasm_V1beta1_MsgClearContractAdmin,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgClearContractAdmin, Terra_Wasm_V1beta1_MsgClearContractAdminResponse>
}

extension Terra_Wasm_V1beta1_MsgClientProtocol {
  internal var serviceName: String {
    return "terra.wasm.v1beta1.Msg"
  }

  /// StoreCode to submit Wasm code to the system
  ///
  /// - Parameters:
  ///   - request: Request to send to StoreCode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func storeCode(
    _ request: Terra_Wasm_V1beta1_MsgStoreCode,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgStoreCode, Terra_Wasm_V1beta1_MsgStoreCodeResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/StoreCode",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStoreCodeInterceptors() ?? []
    )
  }

  /// MigrateCode to submit new version Wasm code to the system
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateCode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func migrateCode(
    _ request: Terra_Wasm_V1beta1_MsgMigrateCode,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgMigrateCode, Terra_Wasm_V1beta1_MsgMigrateCodeResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/MigrateCode",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateCodeInterceptors() ?? []
    )
  }

  ///  Instantiate creates a new smart contract instance for the given code id.
  ///
  /// - Parameters:
  ///   - request: Request to send to InstantiateContract.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func instantiateContract(
    _ request: Terra_Wasm_V1beta1_MsgInstantiateContract,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgInstantiateContract, Terra_Wasm_V1beta1_MsgInstantiateContractResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/InstantiateContract",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeInstantiateContractInterceptors() ?? []
    )
  }

  /// Execute submits the given message data to a smart contract
  ///
  /// - Parameters:
  ///   - request: Request to send to ExecuteContract.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func executeContract(
    _ request: Terra_Wasm_V1beta1_MsgExecuteContract,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgExecuteContract, Terra_Wasm_V1beta1_MsgExecuteContractResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/ExecuteContract",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecuteContractInterceptors() ?? []
    )
  }

  /// Migrate runs a code upgrade/ downgrade for a smart contract
  ///
  /// - Parameters:
  ///   - request: Request to send to MigrateContract.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func migrateContract(
    _ request: Terra_Wasm_V1beta1_MsgMigrateContract,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgMigrateContract, Terra_Wasm_V1beta1_MsgMigrateContractResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/MigrateContract",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMigrateContractInterceptors() ?? []
    )
  }

  /// UpdateContractAdmin sets a new admin for a smart contract
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateContractAdmin.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateContractAdmin(
    _ request: Terra_Wasm_V1beta1_MsgUpdateContractAdmin,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgUpdateContractAdmin, Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/UpdateContractAdmin",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateContractAdminInterceptors() ?? []
    )
  }

  /// ClearContractAdmin remove admin flag from a smart contract
  ///
  /// - Parameters:
  ///   - request: Request to send to ClearContractAdmin.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func clearContractAdmin(
    _ request: Terra_Wasm_V1beta1_MsgClearContractAdmin,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Wasm_V1beta1_MsgClearContractAdmin, Terra_Wasm_V1beta1_MsgClearContractAdminResponse> {
    return self.makeUnaryCall(
      path: "/terra.wasm.v1beta1.Msg/ClearContractAdmin",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClearContractAdminInterceptors() ?? []
    )
  }
}

internal protocol Terra_Wasm_V1beta1_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'storeCode'.
  func makeStoreCodeInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgStoreCode, Terra_Wasm_V1beta1_MsgStoreCodeResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateCode'.
  func makeMigrateCodeInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgMigrateCode, Terra_Wasm_V1beta1_MsgMigrateCodeResponse>]

  /// - Returns: Interceptors to use when invoking 'instantiateContract'.
  func makeInstantiateContractInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgInstantiateContract, Terra_Wasm_V1beta1_MsgInstantiateContractResponse>]

  /// - Returns: Interceptors to use when invoking 'executeContract'.
  func makeExecuteContractInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgExecuteContract, Terra_Wasm_V1beta1_MsgExecuteContractResponse>]

  /// - Returns: Interceptors to use when invoking 'migrateContract'.
  func makeMigrateContractInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgMigrateContract, Terra_Wasm_V1beta1_MsgMigrateContractResponse>]

  /// - Returns: Interceptors to use when invoking 'updateContractAdmin'.
  func makeUpdateContractAdminInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgUpdateContractAdmin, Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse>]

  /// - Returns: Interceptors to use when invoking 'clearContractAdmin'.
  func makeClearContractAdminInterceptors() -> [ClientInterceptor<Terra_Wasm_V1beta1_MsgClearContractAdmin, Terra_Wasm_V1beta1_MsgClearContractAdminResponse>]
}

internal final class Terra_Wasm_V1beta1_MsgClient: Terra_Wasm_V1beta1_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Terra_Wasm_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the terra.wasm.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Terra_Wasm_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the oracle Msg service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Terra_Wasm_V1beta1_MsgProvider: CallHandlerProvider {
  var interceptors: Terra_Wasm_V1beta1_MsgServerInterceptorFactoryProtocol? { get }

  /// StoreCode to submit Wasm code to the system
  func storeCode(request: Terra_Wasm_V1beta1_MsgStoreCode, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgStoreCodeResponse>

  /// MigrateCode to submit new version Wasm code to the system
  func migrateCode(request: Terra_Wasm_V1beta1_MsgMigrateCode, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgMigrateCodeResponse>

  ///  Instantiate creates a new smart contract instance for the given code id.
  func instantiateContract(request: Terra_Wasm_V1beta1_MsgInstantiateContract, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgInstantiateContractResponse>

  /// Execute submits the given message data to a smart contract
  func executeContract(request: Terra_Wasm_V1beta1_MsgExecuteContract, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgExecuteContractResponse>

  /// Migrate runs a code upgrade/ downgrade for a smart contract
  func migrateContract(request: Terra_Wasm_V1beta1_MsgMigrateContract, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgMigrateContractResponse>

  /// UpdateContractAdmin sets a new admin for a smart contract
  func updateContractAdmin(request: Terra_Wasm_V1beta1_MsgUpdateContractAdmin, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse>

  /// ClearContractAdmin remove admin flag from a smart contract
  func clearContractAdmin(request: Terra_Wasm_V1beta1_MsgClearContractAdmin, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Wasm_V1beta1_MsgClearContractAdminResponse>
}

extension Terra_Wasm_V1beta1_MsgProvider {
  internal var serviceName: Substring { return "terra.wasm.v1beta1.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StoreCode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgStoreCode>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgStoreCodeResponse>(),
        interceptors: self.interceptors?.makeStoreCodeInterceptors() ?? [],
        userFunction: self.storeCode(request:context:)
      )

    case "MigrateCode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgMigrateCode>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgMigrateCodeResponse>(),
        interceptors: self.interceptors?.makeMigrateCodeInterceptors() ?? [],
        userFunction: self.migrateCode(request:context:)
      )

    case "InstantiateContract":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgInstantiateContract>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgInstantiateContractResponse>(),
        interceptors: self.interceptors?.makeInstantiateContractInterceptors() ?? [],
        userFunction: self.instantiateContract(request:context:)
      )

    case "ExecuteContract":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgExecuteContract>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgExecuteContractResponse>(),
        interceptors: self.interceptors?.makeExecuteContractInterceptors() ?? [],
        userFunction: self.executeContract(request:context:)
      )

    case "MigrateContract":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgMigrateContract>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgMigrateContractResponse>(),
        interceptors: self.interceptors?.makeMigrateContractInterceptors() ?? [],
        userFunction: self.migrateContract(request:context:)
      )

    case "UpdateContractAdmin":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgUpdateContractAdmin>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse>(),
        interceptors: self.interceptors?.makeUpdateContractAdminInterceptors() ?? [],
        userFunction: self.updateContractAdmin(request:context:)
      )

    case "ClearContractAdmin":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Wasm_V1beta1_MsgClearContractAdmin>(),
        responseSerializer: ProtobufSerializer<Terra_Wasm_V1beta1_MsgClearContractAdminResponse>(),
        interceptors: self.interceptors?.makeClearContractAdminInterceptors() ?? [],
        userFunction: self.clearContractAdmin(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Terra_Wasm_V1beta1_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'storeCode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStoreCodeInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgStoreCode, Terra_Wasm_V1beta1_MsgStoreCodeResponse>]

  /// - Returns: Interceptors to use when handling 'migrateCode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateCodeInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgMigrateCode, Terra_Wasm_V1beta1_MsgMigrateCodeResponse>]

  /// - Returns: Interceptors to use when handling 'instantiateContract'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeInstantiateContractInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgInstantiateContract, Terra_Wasm_V1beta1_MsgInstantiateContractResponse>]

  /// - Returns: Interceptors to use when handling 'executeContract'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeExecuteContractInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgExecuteContract, Terra_Wasm_V1beta1_MsgExecuteContractResponse>]

  /// - Returns: Interceptors to use when handling 'migrateContract'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMigrateContractInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgMigrateContract, Terra_Wasm_V1beta1_MsgMigrateContractResponse>]

  /// - Returns: Interceptors to use when handling 'updateContractAdmin'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateContractAdminInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgUpdateContractAdmin, Terra_Wasm_V1beta1_MsgUpdateContractAdminResponse>]

  /// - Returns: Interceptors to use when handling 'clearContractAdmin'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeClearContractAdminInterceptors() -> [ServerInterceptor<Terra_Wasm_V1beta1_MsgClearContractAdmin, Terra_Wasm_V1beta1_MsgClearContractAdminResponse>]
}
