// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: terra/market/v1beta1/market.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Params defines the parameters for the market module.
public struct Terra_Market_V1beta1_Params {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var basePool: Data = Data()

  public var poolRecoveryPeriod: UInt64 = 0

  public var minStabilitySpread: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Terra_Market_V1beta1_Params: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "terra.market.v1beta1"

extension Terra_Market_V1beta1_Params: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Params"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "base_pool"),
    2: .standard(proto: "pool_recovery_period"),
    3: .standard(proto: "min_stability_spread"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.basePool) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.poolRecoveryPeriod) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.minStabilitySpread) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.basePool.isEmpty {
      try visitor.visitSingularBytesField(value: self.basePool, fieldNumber: 1)
    }
    if self.poolRecoveryPeriod != 0 {
      try visitor.visitSingularUInt64Field(value: self.poolRecoveryPeriod, fieldNumber: 2)
    }
    if !self.minStabilitySpread.isEmpty {
      try visitor.visitSingularBytesField(value: self.minStabilitySpread, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Terra_Market_V1beta1_Params, rhs: Terra_Market_V1beta1_Params) -> Bool {
    if lhs.basePool != rhs.basePool {return false}
    if lhs.poolRecoveryPeriod != rhs.poolRecoveryPeriod {return false}
    if lhs.minStabilitySpread != rhs.minStabilitySpread {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
