//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: terra/market/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the market Msg service.
///
/// Usage: instantiate `Terra_Market_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Terra_Market_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Terra_Market_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func swap(
    _ request: Terra_Market_V1beta1_MsgSwap,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Market_V1beta1_MsgSwap, Terra_Market_V1beta1_MsgSwapResponse>

  func swapSend(
    _ request: Terra_Market_V1beta1_MsgSwapSend,
    callOptions: CallOptions?
  ) -> UnaryCall<Terra_Market_V1beta1_MsgSwapSend, Terra_Market_V1beta1_MsgSwapSendResponse>
}

extension Terra_Market_V1beta1_MsgClientProtocol {
  internal var serviceName: String {
    return "terra.market.v1beta1.Msg"
  }

  /// Swap defines a method for swapping coin from one denom to another
  /// denom.
  ///
  /// - Parameters:
  ///   - request: Request to send to Swap.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func swap(
    _ request: Terra_Market_V1beta1_MsgSwap,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Market_V1beta1_MsgSwap, Terra_Market_V1beta1_MsgSwapResponse> {
    return self.makeUnaryCall(
      path: "/terra.market.v1beta1.Msg/Swap",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSwapInterceptors() ?? []
    )
  }

  /// SwapSend defines a method for swapping and sending coin from a account to other
  /// account.
  ///
  /// - Parameters:
  ///   - request: Request to send to SwapSend.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func swapSend(
    _ request: Terra_Market_V1beta1_MsgSwapSend,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Terra_Market_V1beta1_MsgSwapSend, Terra_Market_V1beta1_MsgSwapSendResponse> {
    return self.makeUnaryCall(
      path: "/terra.market.v1beta1.Msg/SwapSend",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSwapSendInterceptors() ?? []
    )
  }
}

internal protocol Terra_Market_V1beta1_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'swap'.
  func makeSwapInterceptors() -> [ClientInterceptor<Terra_Market_V1beta1_MsgSwap, Terra_Market_V1beta1_MsgSwapResponse>]

  /// - Returns: Interceptors to use when invoking 'swapSend'.
  func makeSwapSendInterceptors() -> [ClientInterceptor<Terra_Market_V1beta1_MsgSwapSend, Terra_Market_V1beta1_MsgSwapSendResponse>]
}

internal final class Terra_Market_V1beta1_MsgClient: Terra_Market_V1beta1_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Terra_Market_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the terra.market.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Terra_Market_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the market Msg service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Terra_Market_V1beta1_MsgProvider: CallHandlerProvider {
  var interceptors: Terra_Market_V1beta1_MsgServerInterceptorFactoryProtocol? { get }

  /// Swap defines a method for swapping coin from one denom to another
  /// denom.
  func swap(request: Terra_Market_V1beta1_MsgSwap, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Market_V1beta1_MsgSwapResponse>

  /// SwapSend defines a method for swapping and sending coin from a account to other
  /// account.
  func swapSend(request: Terra_Market_V1beta1_MsgSwapSend, context: StatusOnlyCallContext) -> EventLoopFuture<Terra_Market_V1beta1_MsgSwapSendResponse>
}

extension Terra_Market_V1beta1_MsgProvider {
  internal var serviceName: Substring { return "terra.market.v1beta1.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Swap":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Market_V1beta1_MsgSwap>(),
        responseSerializer: ProtobufSerializer<Terra_Market_V1beta1_MsgSwapResponse>(),
        interceptors: self.interceptors?.makeSwapInterceptors() ?? [],
        userFunction: self.swap(request:context:)
      )

    case "SwapSend":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Terra_Market_V1beta1_MsgSwapSend>(),
        responseSerializer: ProtobufSerializer<Terra_Market_V1beta1_MsgSwapSendResponse>(),
        interceptors: self.interceptors?.makeSwapSendInterceptors() ?? [],
        userFunction: self.swapSend(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Terra_Market_V1beta1_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'swap'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSwapInterceptors() -> [ServerInterceptor<Terra_Market_V1beta1_MsgSwap, Terra_Market_V1beta1_MsgSwapResponse>]

  /// - Returns: Interceptors to use when handling 'swapSend'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSwapSendInterceptors() -> [ServerInterceptor<Terra_Market_V1beta1_MsgSwapSend, Terra_Market_V1beta1_MsgSwapSendResponse>]
}
